services:
  - type: static_site
    name: kulu-ilan
    env: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # Vite/React SPA yönlendirmesi: tüm yolları index.html'e düşür
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
