export const NEIGHBORHOODS = [
  'ACIKUYU MAHALLESİ', 'ALPARSLAN MAHALLESİ', 'ALTILAR MAHALLESİ', 'ARŞINCI MAHALLESİ', 'BAHADIRLI MAHALLESİ',
  'BEŞKARDEŞ MAHALLESİ', 'BOZAN MAHALLESİ', 'BURUNAĞIL MAHALLESİ', 'CAMİKEBİR MAHALLESİ', 'CANIMANA MAHALLESİ',
  'CELEP MAHALLESİ', 'CUMHURİYET MAHALLESİ', 'DEĞİRMENÖZÜ MAHALLESİ', 'DİNEK MAHALLESİ', 'DİPDEDE MAHALLESİ',
  'DOĞUTEPE MAHALLESİ', 'FATİH SULTAN MEHMET MAHALLESİ', 'FEVZİYE MAHALLESİ', 'GÖKLER MAHALLESİ', 'GÜZELYAYLA MAHALLESİ',
  'HİSARKÖY MAHALLESİ', 'KARACADAĞ MAHALLESİ', 'KARACADERE MAHALLESİ', 'KARAPINAR MAHALLESİ', 'KARŞIYAKA MAHALLESİ',
  'KEMALİYE MAHALLESİ', 'KIRKKUYU MAHALLESİ', 'KIRKPINAR MAHALLESİ', 'KOZANLI MAHALLESİ', 'KÖMÜŞİNİ MAHALLESİ',
  'KÖSTENGİL MAHALLESİ', 'KÖŞKER MAHALLESİ', 'MANDIRA MAHALLESİ', 'ÖMERANLI MAHALLESİ', 'SARIYAYLA MAHALLESİ',
  'SEYİTAHMETLİ MAHALLESİ', 'SOĞUKKUYU MAHALLESİ', 'ŞEREFLİ MAHALLESİ', 'TAVLIÖREN MAHALLESİ', 'TUZYAKA MAHALLESİ',
  'YARAŞLI MAHALLESİ', 'YAZIÇAYIR MAHALLESİ', 'YENİ MAHALLESİ', 'YEŞİLTEPE MAHALLESİ', 'YEŞİLYURT MAHALLESİ',
  'ZİNCİRLİKUYU MAHALLESİ'
]


